Feature/create route and controller password recovery
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #11
Opened 2023-10-27 21:20 UTC by skrowll

2023-10-27 21:21 UTC, skrowll commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Criação de rota + Controller](https://trello.com/c/sVQyU9Bb/319-orion-marte-cria%C3%A7%C3%A3o-de-rota-controller)

2023-10-27 22:15 UTC, samuelcamilocosta requested changes

2023-10-27 22:15 UTC, samuelcamilocosta commented on src/controller/RecoveryController.ts
> +    console.log(token);
remover o console.log do código

2023-10-27 22:15 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
>      await MysqlDataSource.getRepository(User).update(user.id, user);
O update aqui está sendo realizado com todos os dados do usuário, isso faz com que o Hash do usuário seja salvo como senha do usuário, então uma pessoa qualquer se pedisse uma recuperação de senha para o seu e-mail, o seu usuário não funcionaria.

a melhor forma de salvar o dado aqui, seria igual foi feito no saveAccessTokenInUser
```update(user.id, { passwordRecoveryToken: token })```

2023-10-28 13:35 UTC, samuelcamilocosta approved these changes

2023-10-28 13:39 UTC, merged