feat: create middleware to validate accessToken
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #14
Opened 2023-10-31 02:14 UTC by skrowll

2023-10-31 02:15 UTC, skrowll commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Criar middleware para validar accessToken](https://trello.com/c/YpnzvsW6/278-orion-marte-criar-middleware-para-validar-acesstoken)

2023-11-01 21:51 UTC, samuelcamilocosta requested changes

2023-11-01 21:51 UTC, samuelcamilocosta commented on src/middlewares/authValidation.ts
> + * @returns A Promise that resolves if the authentication is successful or sends an error response if it fails.
Quando o retorno é void, não precisa adicioná-lo na documentação

2023-11-01 21:51 UTC, samuelcamilocosta commented on src/middlewares/authValidation.ts
> +  const { email } = req.body;
aquele ponto de que os endpoints não receberão sempre o parâmetro de e-mail para fazer essa validação, então teria que decodificar o token, pegar o id do usuário e utilizá-lo para encontrar o usuário, em vez de buscar o usuário pelo email

2023-11-07 00:15 UTC, samuelcamilocosta requested changes

2023-11-07 00:15 UTC, samuelcamilocosta commented on src/library/jwtUtils.ts
> +      const verified = jwt.verify(token, secretKey);
pode simplificar evitando criar uma const
return jwt.verify(token, secretKey);

2023-11-07 00:15 UTC, samuelcamilocosta commented on src/library/jwtUtils.ts
> +   * @throws If the token is invalid or an error occurs during verification, an error object is returned.
a função não possui throw, pois em caso de erro, retornará um objeto contendo o erro, por isso pode remover o @throws

2023-11-07 21:12 UTC, samuelcamilocosta approved these changes

2023-11-07 21:12 UTC, merged