Feature/refactor tsdocs
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #17
Opened 2023-11-09 13:21 UTC by Ricardonovais1

Esta PR tem o objetivo de refatorar as documentações (TSdocs) de funções e classes.

2023-11-09 13:23 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION-MARTE] - Refatorar TSdocs](https://trello.com/c/zq3SUs7E/501-orion-marte-refatorar-tsdocs)

2023-11-09 22:06 UTC, samuelcamilocosta requested changes

2023-11-09 22:06 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
>     * @param email used as reference to find the user.
Os parâmetros dessa função são userId e Token e o retorno é um UpdateResult.
Ambos estão documentados errados aqui

2023-11-09 22:06 UTC, samuelcamilocosta commented on src/middlewares/validationMiddleware.ts
>   * (Minimum 8 chars, 1 uppercase, 1 lowercase, 1 number and 1 special character)
A explicação da regex deve acompanhar a descrição da função, aqui nesse local em que ela está, dá a entender que retornará esses critérios na função

2023-11-10 21:55 UTC, samuelcamilocosta approved these changes

2023-11-10 21:55 UTC, samuelcamilocosta requested changes
Resolver conflitos

2023-11-10 22:27 UTC, samuelcamilocosta approved these changes

2023-11-10 22:27 UTC, merged