Feature/create user entity and migrations
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #2
Opened 2023-10-18 17:17 UTC by skrowll

2023-10-18 17:18 UTC, skrowll commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Criar Entidade e migration de Usuário.](https://trello.com/c/yopV5U32/275-orion-marte-criar-entidade-e-migration-de-usu%C3%A1rio)

2023-10-18 21:30 UTC, samuelcamilocosta requested changes

2023-10-18 21:30 UTC, samuelcamilocosta commented on src/migration/1697643929272-createUsers.ts
> +export class CreateUsers1697643929272 implements MigrationInterface {
Pode deletar esse arquivo de migration createUsers, pois ele criaria a tabela de 'users', o código do entity/Users.ts é responsável por fazer isso, então não é necessário essa migration

2023-10-18 21:30 UTC, samuelcamilocosta commented on src/migration/1697645895089-userDataPopulation.ts
> +    password: '123456'
Se o formulário do front-end para login permitir o disparo de senha, somente com os critérios mínimos de senha obrigatório, você não conseguirá logar com esses usuários, já que as senhas deles não correspondem aos requisitos mínimos de senha necessária

2023-10-18 21:30 UTC, samuelcamilocosta commented on src/migration/1697645895089-userDataPopulation.ts
> +        'INSERT INTO users (email, password) VALUES (?, ?)',
Dependendo da quantidade de dados que possuir, pode acabar tornando custoso escrever uma query SQL na mão, então recomendo a já ir acostumando com os métodos do TypeORM para inserção de dados

Uma solução alternativa
      `queryRunner.manager.save('Users', { email: user.email, password: user.password });`

2023-10-18 21:30 UTC, samuelcamilocosta commented on src/migration/1697645895089-userDataPopulation.ts
> +      await queryRunner.query('DELETE FROM users WHERE email = ?', [
A alternativa para essa query, seria
`await queryRunner.manager.delete('Users', { email: user.email });`

2023-10-18 21:30 UTC, samuelcamilocosta commented on src/migration/1697645895089-userDataPopulation.ts
> +export class UserDataPopulation1697645895089 implements MigrationInterface {
Faltou adicionar TSDoc as funções, utilize o padrão abaixo
```

/**
* (Nome da função)
*
* (Breve descrição do que a função faz)
*
* (Parâmetros da função)
*
* (Retorno esperado da função) se for void, não é necessário
*/
```

2023-10-19 19:18 UTC, samuelcamilocosta approved these changes

2023-10-19 19:18 UTC, merged