Feat: endpoint POST for PlanCards
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #29
Opened 2023-11-16 10:01 UTC by Ricardonovais1

Esta PR cria o endpoint de POST para criação de novos _PlanCards_ no banco de dados.

2023-11-16 14:43 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] - Criar endpoint POST de dados para os cards dos PLANOS.](https://trello.com/c/V9xJrcDR/539-orion-marte-criar-endpoint-post-de-dados-para-os-cards-dos-planos)

2023-11-16 22:25 UTC, samuelcamilocosta requested changes

2023-11-16 22:25 UTC, samuelcamilocosta commented on src/repositories/planCardRepository.ts
> +    return await MysqlDataSource.getRepository(PlanCard).save(newPlanCard);
quando se faz um return, não há a necessidade de utilizar o await

2023-11-16 22:25 UTC, samuelcamilocosta commented on src/repositories/planCardRepository.ts
> +    const newPlanCard: PlanCard = new PlanCard();
O repositório, é utilizado para gerar 'queries' para comunicação com o backend, então essa parte de se criar um objeto para ser adicionado ao banco, faz mais sentido estar no controller

2023-11-16 22:25 UTC, samuelcamilocosta commented on src/api/v1/newPlanCardRoute.ts
> +router.post('/new-plan-card', PlanCardController.createPlanCard);
Faltou o middleware validação e tratamento dos valores recebidos pelo endpoint

2023-11-17 03:36 UTC, samuelcamilocosta requested changes

2023-11-17 03:36 UTC, samuelcamilocosta commented on src/controller/PlanCardController.ts
> +      await MysqlDataSource.getRepository(PlanCard).save(newPlanCard);
Em casos de cadastro assim, retorne o objeto criado e não o objeto que você passou para o repositório
Eles terão diferenças entre si, já que pode conter alguma manipulação na inserção ou na entidade como valores de campo 'default', um exemplo seria a role do usuário, mesmo cadastrando um usuário sem role, ele será retornado com role de free por default

```
const createdPlanCard = await MysqlDataSource.getRepository(PlanCard).save(newPlanCard);
res.status(201).json(createdPlanCard);
```

2023-11-17 03:36 UTC, samuelcamilocosta commented on src/controller/PlanCardController.ts
> +      const newPlanCard: PlanCard = new PlanCard();
Se criar o objeto assim, não agrada mais visualmente?

  const newPlanCard: PlanCard = {
    planCardTitle,
    planCardDescription,
    planCardImage,
    planCardButtonText,
  };

2023-11-17 03:36 UTC, samuelcamilocosta commented on src/controller/PlanCardController.ts
> +    const { planCardTitle, planCardDescription, planCardImage, planCardButtonText } = req.body;
Tem que criar um middleware de validação para esse endpoint para tratar os valores recebidos

2023-11-17 12:04 UTC, Ricardonovais1 commented on src/controller/PlanCardController.ts
> +      const newPlanCard: PlanCard = new PlanCard();
Verdade, esqueci que era possível fazer isso!

2023-11-17 12:10 UTC, Ricardonovais1 commented on src/controller/PlanCardController.ts
> +      const newPlanCard: PlanCard = new PlanCard();
Conssegui fazer mas apenas quando o tipo foi DeepPartial<PlanCard>

2023-11-21 23:38 UTC, samuelcamilocosta approved these changes

2023-11-21 23:38 UTC, merged