Feat:  Added POST endpoint for home page cards creation
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #31
Opened 2023-11-16 13:49 UTC by GabrielSgrancio

2023-11-16 22:41 UTC, samuelcamilocosta requested changes

2023-11-16 22:41 UTC, samuelcamilocosta commented on src/api/v1/HomePageCardsRoute.ts
> +const homePageCardRepository = new HomePageCardRepository();
por que chamou o HomeCardRepository aqui?

2023-11-16 22:41 UTC, samuelcamilocosta commented on src/controller/HomePageCardController.ts
> +  constructor(homePageCardRepository: HomePageCardRepository) {
não há necessidade de inicializar o repositório ao ler os endpoints com um constructor aqui, ele só irá poluir o seu código visualmente

2023-11-16 22:41 UTC, samuelcamilocosta commented on src/controller/HomePageCardController.ts
> +      const homePageCards = await this.homePageCardRepository.findAllHomePageCards();
const homePageCards = await new HomePageCardRepository().findAllHomePageCards();

2023-11-16 22:41 UTC, samuelcamilocosta commented on src/api/v1/HomePageCardsRoute.ts
> +router.post('/create-home-page-card', (req, res) => homePageCardController.createHomePageCard(req, res));
faltou criar o middleware de validação para os dados recebidos para criar card

2023-11-16 22:41 UTC, samuelcamilocosta commented on src/repositories/homePageCardRepository.ts
> +  async findAllHomePageCards(): Promise<HomePageCard[]> {
as funções do repositório podem ser públicas para serem acessadas sem precisar inicializá-lo em uma classe

2023-11-16 23:11 UTC, GabrielSgrancio commented on src/api/v1/HomePageCardsRoute.ts
> +const homePageCardRepository = new HomePageCardRepository();
Eu estava lendo sobre Dependency Injection e tentei aplicar algo parecido aí, vou alterar.

2023-11-16 23:12 UTC, GabrielSgrancio commented on src/controller/HomePageCardController.ts
> +  constructor(homePageCardRepository: HomePageCardRepository) {
Eu estava lendo sobre Dependency Injection e tentei aplicar algo parecido aí, vou alterar.

2023-11-17 03:23 UTC, samuelcamilocosta requested changes

2023-11-17 03:23 UTC, samuelcamilocosta commented on src/repositories/homePageCardRepository.ts
> +    return this.repository.save(newCard);
return this.repository.save(this.repository.create(card));

2023-11-17 22:12 UTC, samuelcamilocosta requested changes

2023-11-17 22:12 UTC, samuelcamilocosta commented on src/middlewares/homePageCardPostValidation.ts
> +  body('description').notEmpty().isString().trim().isLength({ max: 500 }),
Se eu passar uma string de 500 caracteres, o seu banco irá salvar? o valor limite deve ser setado na hora de criar o @Column, caso contrário ele usará um valor default do banco que estiver utilizando, isso cortaria a descrição

2023-11-17 22:12 UTC, samuelcamilocosta commented on src/migration/1700052154823-AddHomePageCards.ts
> +  /**
Faltou uma linha de espaçamento aqui

2023-11-17 22:12 UTC, samuelcamilocosta commented on src/controller/HomePageCardController.ts
> +      const homePageCard = await HomePageCardRepository.createHomePageCard(req.body);
Você está passando o req.body diretamente para o cadastro dos bancos sem montar o objeto de card que será criado anteriormente, isso pode induzir a criação de erro na hora de gerar o objeto

2023-11-18 17:42 UTC, samuelcamilocosta requested changes

2023-11-18 17:42 UTC, samuelcamilocosta commented on src/api/v1/HomePageCardsRoute.ts
> +router.get('/get-home-page-cards', HomePageCardController.findAllHomePageCards);
para finalizar na história de acordo com as regras de negócio, as rotas precisam estar protegidas com o middleware de autenticação

2023-11-18 17:42 UTC, samuelcamilocosta commented on src/controller/HomePageCardController.ts
> +      const homePageCard = await HomePageCardRepository.createHomePageCard(req.body);
É bom fazer essa criação do objeto a ser salvo aqui no controller e não no middleware

2023-11-21 22:16 UTC, samuelcamilocosta approved these changes

2023-11-21 22:16 UTC, merged