feat: protect solesRoute with bearer auth
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #32
Opened 2023-11-16 14:44 UTC by Ricardonovais1

Esta PR faz a proteção da rota dos soles.

2023-11-16 14:46 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Proteção da rota soles](https://trello.com/c/3ciW6v4B/635-orion-marte-prote%C3%A7%C3%A3o-da-rota-soles)

2023-11-16 22:18 UTC, samuelcamilocosta requested changes

2023-11-16 22:18 UTC, samuelcamilocosta commented on src/controller/SolController.ts
> +      const accessToken: string = req.headers.authorization;
Ao adicionar o middleware de  rota de autenticação isso aqui não é para ser necessário para proteger o endpoint, se estiver sendo necessário essa verificação, algo está acontecendo errado.

2023-11-17 03:18 UTC, samuelcamilocosta approved these changes

2023-11-17 03:20 UTC, samuelcamilocosta approved these changes

2023-11-17 03:20 UTC, merged