Feat: User registration endpoint
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #33
Opened 2023-11-16 20:34 UTC by Ricardonovais1

Esta PR cria o endpoint de registro de usuários.

2023-11-16 20:36 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Endpoint Registro de usuários](https://trello.com/c/aZfg1h4o/639-orion-marte-endpoint-registro-de-usu%C3%A1rios)

2023-11-17 03:17 UTC, samuelcamilocosta requested changes

2023-11-17 03:17 UTC, samuelcamilocosta commented on src/api/v1/userRegistrationRoute.ts
> +router.post('/user-registration', UserRegistrationController.userRegistraton);
Está faltando o Middleware de validação para validar se as informações de e-mail e senha são válidas

2023-11-17 03:17 UTC, samuelcamilocosta commented on src/controller/UserRegistrationController.ts
> +   *                 planCard:
planCard não pertence a resposta do endpoint

2023-11-17 03:17 UTC, samuelcamilocosta commented on src/controller/UserRegistrationController.ts
> +      res.status(201).json(newUser);
Remover a senha do usuário do retorno ao front-end por questões de segurança

2023-11-17 03:17 UTC, samuelcamilocosta commented on src/controller/UserRegistrationController.ts
> +      const newUser: User = await UserRepository.addUser(email, password);
E se eu passar um email que já tenha um usuário cadastrado com ele? 
isso irá atualizar a senha através do email? duplicará o usuário tendo dois usuários no banco?
É necessário um tratamento para essa finalidade

2023-11-17 03:17 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
> +    const newUser: User = new User();
A criação do usuário é melhor sendo feita no endpoint

2023-11-17 03:17 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
> +    return await MysqlDataSource.getRepository(User).save(newUser);
não é necessário utilizar o await quando se usa o return

```return MysqlDataSource.getRepository(User).save(newUser); ```

2023-11-21 22:08 UTC, samuelcamilocosta requested changes

2023-11-21 22:08 UTC, samuelcamilocosta commented on src/middlewares/userRegistrationMiddleware.ts
> +export class UserRegistrationValidations {
faltou documentar as funções e a classe desse arquivo

2023-11-21 22:08 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
> +    return MysqlDataSource.getRepository(User).findOne({ where: { email } }) || null;
por que alterou de findOneBy para findOne e colocou o || null? esses retornos usando o || null é considerado uma má prática colocado dessa forma

2023-11-22 21:47 UTC, samuelcamilocosta requested changes

2023-11-22 21:47 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +      return res.status(400).send('E-mail e/ou senha inválidos');
Os outros erros estão sendo retornados como 
```{ message: 'E-mail e/ou senha inválidos' } ```
Se quebrar esse padrão esperado, pode quebrar o tratamento do front-end por só retornar uma string direto, em vez de um objeto contendo o message

2023-11-22 21:47 UTC, samuelcamilocosta commented on src/middlewares/userRegistrationMiddleware.ts
>      if (emailOrPasswordInvalid) {
Essa validação não é a mesma feita pelo endpoint de login? Como que no login para ser inválido tem que utilizar o ! e aqui para ser inválido não precisa? Uma das duas comparações estará errada assim

2023-11-22 21:47 UTC, samuelcamilocosta commented on src/middlewares/validationMiddleware.ts
> +  public static async validateEmailAndPassword(email: string, password: string): Promise<boolean> {
não há necessidade dessa função ser assíncrona, o retorno dela será booleano já que é uma comparação direta por meio de regex e não promise<boolean>

2023-11-22 22:54 UTC, samuelcamilocosta approved these changes

2023-11-24 19:35 UTC, samuelcamilocosta approved these changes

2023-11-24 19:36 UTC, merged