Feature/criar rota v1 login
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #4
Opened 2023-10-18 21:59 UTC by Ricardonovais1

Criação de rota v1/login

Arquivo na pasta api/v1/loginRoute.ts

Array de erros: 

![image](https://github.com/samuelcamilocosta/orion-bootcamp-back-boilerplate/assets/43175373/342ee5b8-18db-4d6d-bc99-afbefd4188f2)

Mensagem de sucesso: 

![image](https://github.com/samuelcamilocosta/orion-bootcamp-back-boilerplate/assets/43175373/595f4872-5ce7-4712-bdc1-d04e3cba818c)

2023-10-19 22:46 UTC, samuelcamilocosta requested changes

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/api/v1/loginRoute.ts
> +// import { body } from 'express-validator';
não deixe trechos de código comentado, se não está sendo utilizado, melhor removê-lo

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +// import { validationResult } from 'express-validator';
remover trecho de código não utilizado

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +  /**
A documentação do endpoint será o Swagger, então não há necessidade de documentar a função do endpoint usando também o TSDoc.
Pode remover essa documentação da linha 61 a 88, pois ela reafirma o que foi documentado com o Swagger

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +    // const errors = validationResult(req);
remover o trecho de código comentado, já que não está sendo utilizado

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +   * /login:
a rota será /v1/login não?

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +   *     tags: [Home]
no tags: [Login] ou [User] ou [Auth] seria o mais correto para referenciar ao login

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +   *     summary: User login
Pode detalhar melhor a ação que será realizada no login aqui no summary

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +  public static login(req: Request, res: Response) {
Adicionar a tipagem de retorno esperado pela função.
Por que ela é static?

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/middlewares/validationMiddleware.ts
> +export function validateEmailAndPassword(email, password): boolean {
qual a tipagem esperada dos parâmetros de email e password?

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/middlewares/validationMiddleware.ts
> +function validateEmail(email): boolean {
qual a tipagem esperada pelo parâmetro  de email?

2023-10-19 22:46 UTC, samuelcamilocosta commented on src/middlewares/validationMiddleware.ts
> +function validatePassword(password): boolean {
adicionar a tipagem esperada pelo parâmetro de password

2023-10-20 00:33 UTC, Ricardonovais1 commented on src/controller/LoginController.ts
> +  public static login(req: Request, res: Response) {
Melhorei isso. Coloquei static para poder chamar a função login diretamente dentro da classe no arquino loginReoute.ts.

2023-10-20 16:04 UTC, samuelcamilocosta requested changes

2023-10-20 16:04 UTC, samuelcamilocosta commented on tsconfig.json
>  {
você puxou alterações da develop, acabou diferenciando dos dados que você tinha na sua branch e gerou um conflito, aqui está aparecendo que o conflito foi commitado em vez de ser resolvido, então tem que resolver esse conflito para realizar o merge, caso contrário adicionará um erro ao arquivo tsconfig.json

2023-10-20 16:20 UTC, samuelcamilocosta approved these changes

2023-10-20 16:21 UTC, merged