Feature/create endpoint to create and delete plans
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #43
Opened 2023-11-30 23:28 UTC by skrowll

2023-11-30 23:29 UTC, skrowll commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] - criar endpoint para remover planos](https://trello.com/c/ttk3Gf1H/725-orion-marte-criar-endpoint-para-remover-planos)

2023-12-01 22:53 UTC, samuelcamilocosta requested changes

2023-12-01 22:53 UTC, samuelcamilocosta commented on src/controller/PlanController.ts
> +    const planData = req.body;
tem que puxar as variáveis e criar o objeto de planData, se não você vai puxar qualquer valor que inserirem no body, mesmo variáveis não tratadas pelo validator e isso abriria vulnerabilidade

2023-12-01 22:53 UTC, samuelcamilocosta commented on src/api/v1/plansRoute.ts
> +router.delete('/plans/:id', AuthMiddleware.authValidation, PlanController.deletePlanById);
Tem que criar os validators para tratar os valores recebidos pelo endpoint

2023-12-01 22:53 UTC, samuelcamilocosta commented on src/middlewares/planPostValidation.ts
> +  public static validatePlan() {
faltou documentar a função e tipar o retorno esperado pela função

2023-12-06 23:28 UTC, samuelcamilocosta approved these changes

2023-12-06 23:29 UTC, merged