feat: password-reset
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #45
Opened 2023-12-02 12:08 UTC by GabrielSgrancio

Adicionada feature de redefinição de senha.
Agora o email enviado pelo endpoint de recovey redireciona o usuário para a página de redefinição de senha, onde ele pode criar uma nova senha que é por sua vez salva no banco, e simultaneamente o RecoveyPassToken é deletado do banco de dados.

2023-12-02 16:01 UTC, samuelcamilocosta approved these changes

2023-12-04 21:06 UTC, samuelcamilocosta requested changes

2023-12-04 21:06 UTC, samuelcamilocosta commented on src/controller/RecoveryController.ts
> +      await UserRepository.deletePasswordRecoveryToken(userId);
no updatePassword você ao setar a nova senha, você já limpa o reoveryToken, então não precisa dessa chamada

2023-12-06 22:06 UTC, GabrielSgrancio commented on src/controller/RecoveryController.ts
> +      await UserRepository.deletePasswordRecoveryToken(userId);
Já está resolvido a chamada duplicada

2023-12-06 22:28 UTC, samuelcamilocosta approved these changes

2023-12-06 22:28 UTC, merged