Feature/add jwt user entity
samuelcamilocosta/orion-bootcamp-back-boilerplate pull request #6
Opened 2023-10-24 10:43 UTC by Ricardonovais1

Fiz esta PR fiz a primeira versão da classe BcryptUtils para refatorar o controller. 
Ainda não fiz a documentação, pois quis apresentar o que fiz até agora e saber se estou no caminho certo.

2023-10-24 14:46 UTC, samuelcamilocosta requested changes

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +class BcryptUtils {
export class BcryptUtils

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +    return jwt.sign(data, secretKey, { expiresIn });
essa função é totalmente relacionada a geração de um JWTToken, então sugiro criar um JWTUtils para assuntos referentes a biblioteca do jsonwebtoken

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +  static async hashPassword(password: string): Promise<string> {
essa função não precisa ser assíncrona

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +   *Generates jwt token, using 'jwt.sign' function. Static to allow to be called inside class itself.
faltou um espaço de distancia em todas as descrições da documentação

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +    const token = await this.generateJWTToken({ userId: userId }, '30m');
o tempo colocado aqui foi de 30 minutos para expiração do token, porém na história o tempo é diferente

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +export default BcryptUtils;
com a exportação da classe lá em cima, não seria necessário a exportação aqui, isso reduziria uma linha no código. Essa é apenas uma sugestão para melhoria (opcional)

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +    const encryptedPassword = await BcryptUtils.hashPassword(password);
essa encriptação da senha, deve ser feita na inserção do usuário ao banco

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +    if (!BcryptUtils.comparePassword(password, encryptedPassword)) {
ficou boa a implementação, mas conseguimos deixar mais descritivos se armazenarmos o resultado da comparação numa variável

```
const passwordsMatch = BcryptUtils.comparePassword(password, encryptedPassword);
if (!passwordsMatch) {
```
facilita a leitura do if dessa forma né?

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +  static async addPasswordRecoveryToken(
essa função poderíamos levar para o repositório do usuário já que a intenção dela é adicionar o token ao usuário e lá, atualizaremos o usuário para salvar o passwordRecoveryToken

2023-10-24 14:46 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +class BcryptUtils {
também é bom adicionarmos as funções se elas são públicas/privadas

se uma função terá uso fora da classe, determine ela como public, se ela será utilizada apenas dentro da classe, determine ela como private

2023-10-24 16:46 UTC, Ricardonovais1 commented on src/library/bcryptUtils.ts
> +   *Generates jwt token, using 'jwt.sign' function. Static to allow to be called inside class itself.
Esses espaços abaixo do nome da classe geram erros no prettier/ eslint

2023-10-24 17:39 UTC, samuelcamilocosta requested changes

2023-10-24 17:39 UTC, samuelcamilocosta commented on src/controller/LoginController.ts
> +     *@userpassword é a senha salva encriptada no banco (ver migration)
não precisa dessa documentação, pois os parâmetros já estão documentados na função do comparePassword

2023-10-24 17:41 UTC, samuelcamilocosta commented on src/library/bcryptUtils.ts
> +   *Generates jwt token, using 'jwt.sign' function. Static to allow to be called inside class itself.
espaço entre o * e o Generates para o texto não ficar colado, está acusando erro de lint?

2023-10-25 20:44 UTC, samuelcamilocosta requested changes

2023-10-25 20:44 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
> +  public static async saveAccessTokenInUser(
faltou a documentação da função

2023-10-25 20:44 UTC, samuelcamilocosta commented on src/repositories/userRepository.ts
> +  public static async findUserByEmail(
faltou a documentação da função

2023-10-25 22:05 UTC, samuelcamilocosta approved these changes

2023-10-25 22:06 UTC, merged